export const styles = {
    container: {
        backgroundColor: 'white',
        borderRadius: '12px',
        padding: '24px',
        marginBottom: '32px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    header: {
        marginBottom: '24px',
    },
    title: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#1f2937',
        margin: 0,
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '14px',
        fontWeight: '500',
        color: '#374151',
    },
    required: {
        color: '#ef4444',
    },
    select: {
        padding: '10px 12px',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        fontSize: '14px',
        backgroundColor: 'white',
        outline: 'none',
    },
    inputError: {
        borderColor: '#ef4444',
    },
    errorText: {
        fontSize: '12px',
        color: '#ef4444',
    },
    itemsSection: {
        borderTop: '1px solid #e5e7eb',
        paddingTop: '16px',
        marginTop: '8px',
    },
    itemRow: {
        display: 'flex',
        gap: '12px',
        alignItems: 'center',
        marginBottom: '12px',
    },
    itemSelect: {
        flex: 2,
        padding: '8px 12px',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        fontSize: '14px',
        outline: 'none',
    },
    itemQuantity: {
        width: '80px',
        padding: '8px 12px',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        fontSize: '14px',
        outline: 'none',
    },
    itemPrice: {
        width: '100px',
        padding: '8px 12px',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        fontSize: '14px',
        outline: 'none',
    },
    removeBtn: {
        padding: '6px 10px',
        backgroundColor: '#fee2e2',
        border: 'none',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: '14px',
        color: '#dc2626',
    },
    addBtn: {
        padding: '8px 16px',
        backgroundColor: '#f3f4f6',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '14px',
        marginTop: '8px',
    },
    buttonGroup: {
        display: 'flex',
        gap: '12px',
        justifyContent: 'flex-end',
        marginTop: '16px',
    },
    cancelBtn: {
        padding: '10px 20px',
        backgroundColor: '#f3f4f6',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        color: '#374151',
        cursor: 'pointer',
    },
    submitBtn: {
        padding: '10px 24px',
        backgroundColor: '#667eea',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        color: 'white',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: '100px',
    },
    loadingSpinner: {
        width: '16px',
        height: '16px',
        border: '2px solid rgba(255,255,255,0.3)',
        borderTopColor: 'white',
        borderRadius: '50%',
        animation: 'pulse 0.8s linear infinite',
        display: 'inline-block',
    },
};